name: Pipeline prueba final
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}

    - name: Debug Terraform Output
      run: terraform output ecr_repository_url
      env:
        TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_TOKEN }}

    - name: Get ECR Repository URL
      id: ecr_url
      run: |
        URL=$(terraform output -raw ecr_repository_url || echo "ERROR")
        echo "DEBUG: ECR_URL=${URL}" # Esto muestra el valor para depuración
        if [ "${URL}" == "ERROR" ]; then
          echo "Failed to fetch ECR URL"
          exit 1
        fi
        echo "ECR_URL=${URL}" >> $GITHUB_ENV
    
    - name: Terraform State Debug
      run: terraform state show module.ecr
      

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'false'
    
    - name: Build Docker image
      run: docker build -f paginaweb-static/Dockerfile -t pruebafinal ./paginaweb-static

    - name: Tag Docker image
      run: docker tag pruebafinal:latest ${{ env.ECR_URL }}/pruebafinal:latest

    - name: Push Docker image to Amazon ECR
      run: docker push ${{ env.ECR_URL }}/pruebafinal:latest